# Generated by Django 4.2.6 on 2023-10-28 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampleprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
