# Generated by Django 4.2.6 on 2023-10-31 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sampleprojectapp', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pdesc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
