# Generated by Django 4.2.6 on 2023-10-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleprojectapp', '0005_image_pdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pdesc',
        ),
    ]
