# Generated by Django 4.2.6 on 2023-11-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleprojectapp', '0006_remove_image_pdesc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='photo',
        ),
    ]
